### ISSUE TITLE
[Bug]: Version 1.4.0 is a breaking change

### ISSUE THREAD

**Issue by juchiast** [metaplex-foundation/mpl-token-auth-rules#134]
### Which package is this bug report for?

sdk

### Issue description

1.3.0 has `processor::cmp_pubkeys`

In 1.4.0, it is moved to `utils::cmp_pubkeys`.

- https://docs.rs/mpl-token-auth-rules/1.3.0/mpl_token_auth_rules/processor/fn.cmp_pubkeys.html
- https://docs.rs/mpl-token-auth-rules/latest/mpl_token_auth_rules/utils/fn.cmp_pubkeys.html

Consequence: `mpl-token-metadata-1.9.1` no longer compiles.

### Relevant log output

```bash
function `cmp_pubkeys` is private

error[E0603]: function `cmp_pubkeys` is private
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mpl-token-metadata-1.9.1/src/processor/metadata/transfer.rs:3:38
   |
3  | use mpl_token_auth_rules::processor::cmp_pubkeys;
   |                                      ^^^^^^^^^^^ private function
   |
note: the function `cmp_pubkeys` is defined here
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mpl-token-auth-rules-1.4.0/src/processor/mod.rs:22:5
   |
22 |     utils::cmp_pubkeys,
   |     ^^^^^^^^^^^^^^^^^^
```
```


### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
If running cargo build doesn't pull the patch version 1.4.1 automatically you can run `cargo update` to fix.
