### ISSUE TITLE
[Bug]: Version 0.2.4 is a breaking change

### ISSUE THREAD

**Issue by juchiast** [metaplex-foundation/mpl-token-auth-rules#76]
### Which package is this bug report for?

program

### Issue description

Version 0.2.4 added a field rule_set_revision to `ValidateArgs::V1`

https://github.com/metaplex-foundation/mpl-token-auth-rules/blob/36a69ab39c63172a2c19c68d7e39d4af5f43682b/program/src/instruction.rs#L34

### Priority this issue should have

Low (slightly annoying)

**Comment by danenbm** [comment]
We are sorry we didn't realize people were as integrated with this lib yet.  We will be more careful in the future about breaking changes now that we know this, and now that we are at 1.x.x
